### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by rayman89** [freddyb/webext-discard-tab#2]
I'm using firefox dev latest version (58) on windows and it's not allowing me to unload any tab.

**Comment by freddyb** [comment]
Hey, @rayman89, thanks for letting me know!

I think this should only work in Nightly as of a few days ago, because it's using a bleeding edge feature.
Nightly identifies as 58.0a1, so I thought that string would allow me to be precise enough in my extension manifest.

Can you share your exact version and build information? about:config has that infromation.
I don't know how often DevEdition updates, but (you'll require a built from after October 31st.](https://bugzilla.mozilla.org/show_bug.cgi?id=1322485#c49).

**Comment by rayman89** [comment]
AFAIK recently Dev version became the same as beta but with the dev features.

![imagen](https://user-images.githubusercontent.com/5449042/32625544-15ba85e0-c552-11e7-97ee-9f8ccc00b8c1.png)

Says firefox is up to date and on aurora channel

on the 7th or 8th of nov firefox beta dev was updated to 58

**Comment by freddyb** [comment]
Hm, yeah. Beta is the wrong branch here. It likely won't get the patch for another week or so.
Sorry, but there's nothing I can do for you now.
But I will ask the addons.mozilla.org folks how to *properly* limit my add-on to Firefoxes newer than Firefox Nightly from Nov 1, 2017.
